libtypec_sysfs_ops: define feature test macro for nftw
According to the man page [1], the definiton of nftw() is
hidden behind the _XOPEN_SOURCE 500 feature test, so we
must enable it to avoid warnings or errors (if the toolchain
is configured to treat them as errors) like this:

/var/tmp/portage/dev-libs/libtypec-0.5.0/work/libtypec-0.5.0-Source/libtypec_sysfs_ops.c:1059:13:
warning: implicit declaration of function ‘nftw’; did you mean ‘ftw’?
[-Wimplicit-function-declaration]
 1059 |         if (nftw ("/dev/bus/usb/", count_billbrd_if, fd_limit, 0) != 0)
      |             ^~~~
      |             ftw

[1] https://linux.die.net/man/3/nftw